development:
  adapter: postgresql
  database: platebot_dev
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: platebot_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: platebot_production
  pool: 5
  timeout: 5000
