undo:
  triggers:
    - undo
    - delete
    - remove
    - remove plate
    - remove late plate
  positive_response: "Got it %{name}, your late plate for %{date} has been removed!"
  negative_response: "%{name}, you don't have any late plates to remove!"

help:
  triggers:
    - howto
    - how to
    - assist
    - halp
    - how
  response: |
    Try something like:
    'Today' - add a late plate for today
    'friday' - add a late for Friday
    'status' - check if you have a plate tonight
    'undo' - remove your most recent addition

add:
  triggers:
    - add
    - new
    - late plate
    - late
    - plate
  negative_response: "%{name}, you already have a late plate for %{date}."
  positive_response: "%{name}, your late plate has been added for %{date}! You can undo this by texting 'undo'. %{nice_phrase}"

status:
  triggers:
    - status
    - check
    - update
  positive_response: "%{name}, you have a late plate added for today!"
  negative_response: "%{name}, you don't have a late plate for today! Text 'add' to add one!"

fetch:
  triggers:
    - fetch
    - fetch all
    - get
    - get all
    - get plates
    - get for tonight
  response: "There %{is_are} %{count} at %{house} today: %{names}"

unknown:
  triggers: []
  response: "Sorry, I didn't get that.  Text 'halp' to see what I understand!"
